### ISSUE TITLE
you forget to return Promise.reject

### ISSUE THREAD

**Issue by ORESoftware** [kevva/executable#11]
wazzup homedogg

https://github.com/kevva/executable/blob/master/index.js#L20

you forgot to return Promise.reject

dynamic languages ftw

I recommend turning this project into a TypeScript project :)

**Comment by ORESoftware** [comment]
i made a PR https://github.com/kevva/executable/pull/12

**Comment by ORESoftware** [comment]
@kevva yo dogg

**Comment by kevva** [comment]
Yo dawg, thanks for the PR :). Unfortunately, this module is pretty small so turning it into a TS project feels a little overkill.

This should be fixed in `4.1.1`!

**Comment by the1mills** [comment]
The smaller the project, I still use TS! That way other people using your API can learn it more easily, for sure
