### ISSUE TITLE
Please add back `executable.sync`

### ISSUE THREAD

**Issue by feross** [kevva/executable#5]
See the [`path-exists`](https://github.com/sindresorhus/path-exists) package for an example where @sindresorhus switched to promises while preserving the `.sync` API.

Here's the commit: https://github.com/sindresorhus/path-exists/commit/f6d0db8c1cbb3f0a4d04b7f8ea616eaf083868fd

**Comment by kevva** [comment]
Oh, didn't thought anyone used that method. Will add it back!

**Comment by feross** [comment]
Awesome, thanks!
