### ISSUE TITLE
Move CLI app to another package?

### ISSUE THREAD

**Issue by feross** [kevva/executable#6]
The dependencies to support the CLI part of this package are quite hefty. `meow` pulls in a lot of stuff, relative to the rest.

Any chance you can publish a separate package `executable-cli` that requires this package, and does the cli stuff? @sindresorhus does this with a lot of his packages.

**Comment by kevva** [comment]
Yup, had this in mind for all my packages that uses a CLI, but hadn't had much time lately.

**Comment by shinnn** [comment]
@kevva You can drop CLI support, publish v3.0.0, and create `executable-cli` *later* :) Users still can use  v2.x for CLI before the separate CLI package is released.

**Comment by kevva** [comment]
https://github.com/kevva/executable-cli
